# Numpy Assignment

1)Write a function so that the columns of the output matrix are powers of the input vector
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N-i-1

In [1]:
import numpy as np

In [2]:
def generate_vander_matrix(ip_vector, n, increasing=False):
    
    if not increasing:
        output_matx = np.array([x**(n-1-i) for x in ip_vector for i in range(n)]).reshape(ip_vector.size,n)
    elif increasing:
        output_matx = np.array([x**i for x in ip_vector for i in range(n)]).reshape(ip_vector.size,n)
    
    return output_matx

In [3]:
input_vector = np.array([1,2,3,4,5])
cols=3
output_desc=generate_vander_matrix(input_vector,cols,False)
print("Output of Descreasing Vander Matrix\n",output_desc)
output_increase=generate_vander_matrix(input_vector,cols,True)
print("Output of Increasing Vander Matrix\n",output_increase)

Output of Descreasing Vander Matrix
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Output of Increasing Vander Matrix
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


2)Write a function to find moving average in an array over a window:        
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
import numpy as np
input_array=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
Moving_avg_sequence_val=len(input_array)-k+1
print("Moving Average Sequence=",Moving_avg_sequence_val)

Moving Average Sequence= 11


In [5]:
def moving_Avg_Sequence(inp_array,k):
    output=[]
    print(" Inputs ".center(40,"*"))
    print("Input Array=",inp_array)
    print("k=",k)
    Moving_avg_sequence_val=len(inp_array)-k+1
    for i in range(Moving_avg_sequence_val):
        pointer=0
        total=0
        while pointer<k:
            total=total+inp_array[pointer+i]
            pointer+=1
        output.append(total/k)
    return output,Moving_avg_sequence_val

In [6]:
output_moving_avg,output_avg_val=moving_Avg_Sequence(input_array,k)
print(" Output ".center(40,"*"))
print("Moving Average Sequence value=",output_avg_val)
print("Moving Average sequence list of values:\n",output_moving_avg)

**************** Inputs ****************
Input Array= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k= 3
**************** Output ****************
Moving Average Sequence value= 11
Moving Average sequence list of values:
 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
